### ISSUE TITLE
Erorr when starting app

### ISSUE THREAD

**Issue by ciokan** [zackehh/sentix#2]
```
** (Mix) Could not start application sentix: Sentix.Application.start(:normal, []) returned an error: shutdown: failed to start child: :exec
    ** (EXIT) bad return value: 'Port program /home/ciokan/Projects/_build/dev/lib/erlexec/priv/x86_64-unknown-linux-gnu/exec-port with SUID bit set is not allowed to run without setting effective user!'
```

**Comment by whitfin** [comment]
@ciokan are you running as root?

I'm coming back to this project tomorrow as there are some incompatibilities I need to fix with Erlang 19, so I'll try figure out what's causing this issue.

I'm actually planning to move away from `:exec` due to things like this.

**Comment by ciokan** [comment]
I'm not running as root though I tried running it as root to see if there's any difference.

**Comment by whitfin** [comment]
@ciokan what's your setup? OS/Erlang/Elixir versions etc?

**Comment by whitfin** [comment]
@ciokan ok pretty sure I narrowed this down; upstream broke it with a change on their end. I just need to make the dependency a little stricter on versioning - will have a fix for you to try shortly.

**Comment by ciokan** [comment]
No worries mate..just learning elixir myself by trying to replace a python app.

**Comment by whitfin** [comment]
@ciokan wanna try use the version in master and see if it works?
