### ISSUE TITLE
Error catching files with spaces in them

### ISSUE THREAD

**Issue by croqaz** [zackehh/sentix#4]
Hello, great lib, great work!

I found a bug regarding files with spaces in their names.

It's in lib/watcher.ex , create_events function. I had a debug message in there like:

> IO.puts "DEBUG EVENT :: #{inspect data}"
> DEBUG EVENT :: "/Users/user/Pictures/icon copy.png Created Updated\n"

And the event emitted is:

> File = "/Users/user/Pictures/icon"
> Events = [:"copy/png", :created, :updated]

Hope this helps.

**Comment by whitfin** [comment]
@croqaz I'm sorry, I totally missed this!

I'll take a look at this as soon as I get some spare time, it should be relatively easy to fix (I think).

**Comment by whitfin** [comment]
Hi @croqaz!

This should be fixed by https://github.com/zackehh/sentix/commit/5cdbb7269e9c53349b5a256728727d7579a76455. Sorry about how long it took to get resolved!

Please try it out and let me know if there are any further issues. Great catch!
